# Generated by Django 5.2.10 on 2026-01-07 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('criteria', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('weight', 'Weight'), ('habit', 'Habit'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_goals', to='athletes.athleteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='athletes.athleteprofile')),
            ],
            options={
                'unique_together': {('athlete', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_type', models.CharField(choices=[('workout', 'Workout'), ('login', 'Login'), ('goal', 'Goal')], max_length=20)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='athletes.athleteprofile')),
            ],
            options={
                'unique_together': {('athlete', 'streak_type')},
            },
        ),
    ]
